require("calvin.plugins-setup")
require("calvin.core.options")
require("calvin.core.keymaps")
require("calvin.plugins.comment")
require("calvin.plugins.nvim-tree")
require("calvin.plugins.lualine")
require("calvin.plugins.mason")
require("calvin.plugins.lsp")
require("calvin.plugins.telescope")
require("calvin.plugins.treesitter")
require("calvin.core.colorscheme")
require("calvin.plugins.which-key")

